#!/usr/bin/env -S sh -c 'docker build --rm -t kungfu.azurecr.io/mw-megatron-lm-data-debug:latest -f $0 .'

FROM kungfu.azurecr.io/mw-megatron-lm-data-commit:latest

# Megatron-LM
WORKDIR /workspace
ADD . Megatron-LM
WORKDIR /workspace/Megatron-LM
