#!/usr/bin/env -S sh -c 'docker build --rm -t kungfu.azurecr.io/mw-megatron-lm-23.06-debug:latest -f $0 .'

FROM kungfu.azurecr.io/mw-megatron-lm-23.06-tenplex:latest

# Megatron-LM
WORKDIR /workspace
ADD . Megatron-LM
WORKDIR /workspace/Megatron-LM
