#!/usr/bin/env -S sh -c 'DOCKER_BUILDKIT=0 docker build --rm -t kungfu.azurecr.io/mw-megatron-lm-23.06-update-v100:latest -f $0 .'

FROM kungfu.azurecr.io/mw-megatron-lm-23.06-tenplex:latest

# Megatron-LM
WORKDIR /workspace
ADD . Megatron-LM
WORKDIR /workspace/Megatron-LM

RUN python compile_kernels.py
