#!/usr/bin/env -S sh -c 'docker build --rm -t kungfu.azurecr.io/mw-megatron-lm-no-scheduler:latest -f $0 .'

FROM kungfu.azurecr.io/mw-megatron-lm-tenplex:latest

# Megatron-LM
WORKDIR /workspace
ADD . Megatron-LM
WORKDIR /workspace/Megatron-LM
