#!/bin/sh

set -e

join_() {
    local IFS=$1
    shift
    echo "$*"
}

join() { join_ , $@; }

gpus() {
    echo 0
    # echo 1
}

name=lg-tenplex-debug
tag=kungfu.azurecr.io/mw-megatron-lm-23.06-debug:latest

docker_run_flags() {
    echo --rm
    echo --gpus
    echo "\"device=$(join $(gpus))\""
    echo -i

    echo --name $name

    echo -v /data:/data
    echo -v $PWD/log:/log
}

docker_run() { docker run $(docker_run_flags) -t $tag $@; }

main() {
    if [ -z "$1" ]; then
        docker_run bash
    else
        docker_run $@
    fi
}

main $@
