#!/usr/bin/env python3
import sys


def f(filename):
    lines = []
    for line in open(filename):
        lines.append(line.rstrip())

    with open(filename, 'w') as f:
        for line in lines:
            f.write(line + '\n')


def main(args):
    for x in args:
        f(x)


main(sys.argv[1:])
